const ARGUMENT_INVALID = "GENERIC.ARGUMENT_INVALID";
const ARGUMENT_OUT_OF_RANGE = "GENERIC.ARGUMENT_OUT_OF_RANGE";
const ARGUMENT_NOT_PROVIDED = "GENERIC.ARGUMENT_NOT_PROVIDED";
const NOT_FOUND = "GENERIC.NOT_FOUND";
const CONFLICT = "GENERIC.CONFLICT";
const INTERNAL_SERVER_ERROR = "GENERIC.INTERNAL_SERVER_ERROR";
const FORBIDDEN = "GENERIC.FORBIDDEN";
const UNPROCESSED_ENTITY = "GENERIC.UNPROCESSED_ENTITY";

module.exports = {
  ARGUMENT_INVALID,
  ARGUMENT_OUT_OF_RANGE,
  ARGUMENT_NOT_PROVIDED,
  NOT_FOUND,
  CONFLICT,
  INTERNAL_SERVER_ERROR,
  FORBIDDEN,
  UNPROCESSED_ENTITY,
};
